let UserItemList= JSON.parse(localStorage.getItem('UserList')) || [];

const PRODUCT=[

    {
        "id":1,
       "img":"https://m.media-amazon.com/images/I/617z5GiMaVS._AC_UL320_.jpg",
       "price":"268",
       "category":"mask",
       "description":"OCRETA Pure Cotton Mask for Men/Women Pack of 6, Skin Friendly Washable , Light Weight & Comfortable.",
    },
    {
        "id":2,
       "img":"https://m.media-amazon.com/images/I/71FZKFwSeRL._AC_UL320_.jpg",
       "price":"499",
       "category":"mask",
       "description":"DALUCI 3Ply Disposable Nonwoven Fabric Face Mask With Nose Clip Certified by CE, ISO & GMP with Bacterial.",
    },
    {
        "id":3,
       "img":"https://m.media-amazon.com/images/I/616K2wXUBZL._AC_UL320_.jpg",
       "price":"200",
       "category":"mask",
       "description":"Jockey Unisex's Cotton Face Mask (Pack of 2).",
    },
    {
        "id":4,
       "img":"https://m.media-amazon.com/images/I/71qshn-Y67L._AC_UL320_.jpg",
       "price":"599",
       "category":"mask",
       "description":"Asgard Nonwoven Fabric Disposable 3 Ply Surgical Mask (Blue, Without Valve, Pack of 100) for Unisex.",
    },
    {
        "id":5,
       "img":"https://m.media-amazon.com/images/I/51xScpHMITL._AC_UL320_.jpg",
       "price":"349",
       "category":"mask",
       "description":"PRAMUKH FASHION Pure Cotton Digital Printed Mask for Men/Women 3 Layers Skin Friendly Washable.",
    },
    {
        "id":6,
       "img":"https://m.media-amazon.com/images/I/51Ff3SLahVL._AC_UL320_.jpg",
       "price":"449",
       "category":"bat",
       "description":"HeadTurners Plastic Bat, Plastic Cricket Bat Hard Plastic, Plastic Bat for Tennis and Wind Ball.",
    },
    {
        "id":7,
       "img":"https://m.media-amazon.com/images/I/71qdmil2ROL._AC_UL320_.jpg",
       "price":"740",
       "category":"bat",
       "description":"Toyshine Dixon Nano RDX Multicolour Popular Willow Full Size Tennis Cricket Bat with Bat Cover (SSTP).",
    },
    {
        "id":8,
       "img":"https://m.media-amazon.com/images/I/61-Ri8bmfvL._AC_UL320_.jpg",
       "price":"399",
       "category":"bat",
       "description":"Lycan Hard Plastic Cricket Bat for 15+ Age Suitable with Tennis Ball, Wind Ball.",
    },
    {
        "id":10,
       "img":"https://m.media-amazon.com/images/I/51fkaRjjrqL._AC_UL320_.jpg",
       "price":"469",
       "category":"bat",
       "description":"Steller Popular Willow Cricket Bat with Tennis Ball and Bat Cover, Full Size.",
    },
    {
        "id":11,
       "img":"https://m.media-amazon.com/images/I/416xX5VVz6L._AC_UL320_.jpg",
       "price":"599",
       "category":"football",
       "description":"VOODANIA Telstar Combo Pack 1 Football & 1 pump PU material multi color size 5 for All Age Groups Kids Fans.",
    },
    {
        "id":12,
       "img":"https://m.media-amazon.com/images/I/61YRTbr7aNL._AC_UL320_.jpg",
       "price":"1419",
       "category":"football",
       "description":"Vector X Maxima Thermo Fusion Football (Size-4).",
    },
    {
        "id":13,
       "img":"https://m.media-amazon.com/images/I/81V5qz2qbhL._AC_UL320_.jpg",
       "price":"349",
       "category":"football",
       "description":"Nivia Storm Football - Size 5.",
    },
    {
        "id":14,
       "img":"https://m.media-amazon.com/images/I/615EoQbGAwS._AC_UL320_.jpg",
       "price":"269",
       "category":"football",
       "description":"Vector X Street Soccer Rubber Moulded Football, Size 5.",
    },
    {
        "id":15,
       "img":"https://m.media-amazon.com/images/I/71ysokdnfNL._AC_UL320_.jpg",
       "price":"590",
       "category":"football",
       "description":"Volatility FCB Hand Stich Football Size-05 with Pump.",
    },
    {
        "id":16,
       "img":"https://m.media-amazon.com/images/I/41tRCHdLteL._AC_UL320_.jpg",
       "price":"140",
       "category":"food",
       "description":"Balaji Wafers Stack Up (Pack of 4) (Simply Salted).",
    },
    {
        "id":17,
       "img":"https://m.media-amazon.com/images/I/81c11zRxbeL._AC_UL320_.jpg",
       "price":"370",
       "category":"food",
       "description":"Flavours of Calicut - Kerala Tapioca (Kappa) Chips - 500g.",
    },
    {
        "id":18,
       "img":"https://m.media-amazon.com/images/I/71lMUEjjhcL._AC_UL320_.jpg",
       "price":"20",
       "category":"food",
       "description":"Balaji Wafers Stack Up (Pack of 4) (Simply Salted).",
    },
    {
        "id":19,
       "img":"https://m.media-amazon.com/images/I/51LBZ+qRWmL._AC_UL320_.jpg",
       "price":"20",
       "category":"food",
       "description":"Lay's Potato Chips, Hot 'n' Sweet Chilli Pouch, 28 g.",
    },
    {
        "id":20,
       "img":"https://m.media-amazon.com/images/I/61jzDf1c7dL._AC_UL320_.jpg",
       "price":"80",
       "category":"food",
       "description":"Dark Fantasy Choco Fills, 300g.",
    },
]


